### ISSUE TITLE
Running with filter reactions give error

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1403]
### Bug Description
Running RMG with filter reactions on generates the following error:
```
Traceback (most recent call last):
  File "/home/mjliu/Code/RMG-Py/rmg.py", line 173, in <module>
    main()
  File "/home/mjliu/Code/RMG-Py/rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/main.py", line 629, in execute
    trimolecular = self.trimolecular,
  File "rmgpy/solver/simple.pyx", line 157, in rmgpy.solver.simple.SimpleReactor.initializeModel
TypeError: initializeModel() got an unexpected keyword argument 'trimolecular'
```

This was presumably introduced by #1338, but was not caught because the examples in RMG-tests do not set filterReactions, which is False by default.

### How To Reproduce
Add `filterReactions=True` to the superminimal input file and run.

**Comment by mliu49** [comment]
Fixed by #1404.
